version: '3'
services:
  api: 
    image: "pluhin/repost-bot-api"
    restart: always
    ports:
      - 8080:8080
    networks:
      - repost-bot-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/repost_bot?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
      tg_bot_token: TG_BOT_TOKEN
      tg_bot_username: TG_BOT_USERNAME
      tg_channel_name: "@TG_CHANNEL_NAME"
      vk_app_id: VK_APP_ID
      vk_app_secret: VK_APP_SECRET
      vk_app_service: VK_APP_SERVICE
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql
  frontend:
    image: "pluhin/repost-bot-frontend"
    restart: always
    ports:
      - 80:80
    networks:
      - repost-bot-network
    environment:
      API_URL: 127.0.0.1:8080

networks:
  repost-bot-network: